version: 2.1

commands:
  update-image:
    description: 'update apt repo'
    steps:
      - run:
          name: Update image
          command: sudo mkdir -p /var/lib/apt/lists/partial ; sudo chmod 755 /var/lib/apt/lists/ ; echo sources.list ; cat /etc/apt/sources.list ; echo sources.list.d ; for file in $(ls /etc/apt/sources.list.d/);do echo $file; cat /etc/apt/sources.list.d/$file;done; sudo rm -rf /etc/apt/sources.list.d/github_git-lfs.list; sudo apt update

  install-bats:
    description: 'install bats from apt'
    steps:
      - run:
          name: Install bats
          command: sudo apt install -y bats

  install-shell-check:
    description: 'install shellcheck from apt'
    steps:
      - run:
          name: Install shellcheck
          command: sudo apt install -y shellcheck

  check-out-prereq:
    description: 'mkdir'
    steps:
      - run:
          name : mkdir destination directory for git checkout
          command: mkdir -p git/docker

  check-out-libshell:
    description: 'check out libshell'
    steps:
      - run:
          name : check ou libshell
          command: mkdir -p git/shell ; git clone https://github.com/cretinon/shell.git git/shell/

  build-result:
    description: 'results of previous build steps'
    steps:
      - run:
          name : Results of previous build steps
          command: type bats ; bats --version ; type shellcheck ; shellcheck --version ; echo -n "pwd:"; pwd ; find .

  run-shellcheck:
    description: 'run shellcheck'
    steps:
      - run:
          name: Run shellcheck
          command: echo "shellcheck git/docker/lib_docker.sh"

  run-bats:
    description: 'run bats'
    steps:
      - run:
          name: Run bats
          command: GIT_DIR="${HOME}/project/git" echo "bats --verbose-run git/docker/bats/tests.bats"

  build-image:
    description: 'test build'
    steps:
      - run:
         name: run build test image
         command: docker build --rm --force-rm --compress -f git/docker/dockerfile/Dockerfile.jinade_base.x86_64.debian -t jinade_base_debian:x86_64 --build-arg ARCH=x86_64 --build-arg DOCKERSRC=jinade_base --build-arg DISTRIB=debian --build-arg REGISTRY=localhost:5000 --build-arg PUID=0 --build-arg PGID=0  --label org.label-schema.build-date=2025-10-24T01:52:35Z --label org.label-schema.name=jinade_base --label org.label-schema.schema-version="1.0"  .

jobs:
  build-and-test:
    docker:
      - image: cimg/base:current
    steps:
      - update-image
      - install-bats
      - install-shell-check
      - check-out-prereq
      - checkout:
          path: git/docker
      - check-out-libshell
      - build-result
      - run-shellcheck
      - run-bats
      - build-image

workflows:
  test-libdocker:
     jobs:
       - build-and-test
