ARG ARCH=frommakefile
ARG DISTRIB=frommakefile
ARG DOCKERSRC=frommakefile
ARG REGISTRY=frommakefile

FROM ${REGISTRY}/${DOCKERSRC}_${DISTRIB}:${ARCH}

RUN apt-get update && apt-get -y -q install --no-install-recommends bind9 bind9-utils && apt-get clean && rm -rf /var/cache/apt/* /var/lib/apt/lists/*

ADD entrypoint/bind9.sh /usr/bin/bind9.sh
RUN chmod +x /usr/bin/bind9.sh

ENTRYPOINT /usr/bin/bind9.sh