ARG ARCH=frommakefile
ARG DISTRIB=frommakefile
ARG DOCKERSRC=frommakefile
ARG REGISTRY=frommakefile

FROM ${REGISTRY}/${DOCKERSRC}_${DISTRIB}:${ARCH}

RUN apt-get update && apt-get -y -q install --no-install-recommends iproute2 netbase net-tools chromium xvfb python-is-python3 wget ca-certificates && apt-get clean && rm -rf /var/cache/apt/* /var/lib/apt/lists/*

RUN mkdir -p /opt/flaresolverr

COPY --chmod=755 entrypoint/flaresolverr.sh /usr/local/bin/

WORKDIR /opt/

RUN wget "https://github.com/FlareSolverr/FlareSolverr/releases/download/v3.3.21/flaresolverr_linux_x64.tar.gz"

RUN tar zxf flaresolverr_linux_x64.tar.gz

WORKDIR /opt/flaresolverr

RUN chmod +x /opt/flaresolverr/flaresolverr

EXPOSE 8191

ENTRYPOINT ["/usr/local/bin/flaresolverr.sh"]
