ARG ARCH=frommakefile
ARG DISTRIB=frommakefile
ARG DOCKERSRC=frommakefile
ARG REGISTRY=frommakefile

FROM ${REGISTRY}/${DOCKERSRC}_${DISTRIB}:${ARCH}

RUN apt-get update
RUN apt-get -y -q install --no-install-recommends emacs
RUN apt-get -y -q install --no-install-recommends curl net-tools procps lsof iproute2 traceroute iputils-ping wget ca-certificates bind9-dnsutils tcpdump
RUN apt-get clean && rm -rf /var/cache/apt/* /var/lib/apt/lists/*

COPY conf/.bashrc /root/
COPY conf/.emacs /root/

