ARG ARCH=frommakefile
ARG DISTRIB=frommakefile
ARG DOCKERSRC=frommakefile
ARG REGISTRY=frommakefile

FROM ${REGISTRY}/${DOCKERSRC}_${DISTRIB}:${ARCH}

RUN apt-get update && apt-get -y -q install --no-install-recommends iproute2 netbase autofs procps nfs-common net-tools transmission-daemon curl ca-certificates && apt-get clean && rm -rf /var/cache/apt/* /var/lib/apt/lists/*

ADD entrypoint/transmission.sh /usr/local/transmission.sh
RUN chmod 755 /usr/local/transmission.sh

RUN echo "/mnt/nfs        /transmission/auto.syno --ghost,--timeout=60" > /etc/auto.master.d/syno.autofs

COPY conf/transmission.json /etc/transmission-daemon/settings.json

EXPOSE 9091/tcp

ENTRYPOINT ["/usr/local/transmission.sh"]
