ARG ARCH
ARG DISTRIB
ARG DOCKERSRC
ARG REGISTRY

ARG HTTP_PROXY
ARG HTTPS_PROXY

FROM ${REGISTRY}/${DOCKERSRC}_${DISTRIB}:${ARCH}
ENV HTTP_PROXY=$HTTP_PROXY
ENV HTTPS_PROXY=$HTTPS_PROXY

RUN apt-get update && apt-get -y -q install --no-install-recommends unzip openjdk-17-jre-headless python-is-python3 wget ca-certificates && apt-get clean && rm -rf /var/cache/apt/* /var/lib/apt/lists/*

# Clear proxy variables for final image
ENV HTTP_PROXY=
ENV HTTPS_PROXY=

RUN mkdir -p /opt/Nzbhydra2

COPY --chmod=755 entrypoint/nzbhydra2.sh /usr/local/bin/

WORKDIR /opt/Nzbhydra2

RUN wget "https://github.com/theotherp/nzbhydra2/releases/download/v7.12.3/nzbhydra2-7.12.3-amd64-linux.zip"

RUN unzip nzbhydra2-7.12.3-amd64-linux.zip

RUN chmod +x /opt/Nzbhydra2/nzbhydra2wrapperPy3.py

EXPOSE 5076

ENTRYPOINT ["/usr/local/bin/nzbhydra2.sh"]
