ARG ARCH=frommakefile
ARG DISTRIB=frommakefile
ARG DOCKERSRC=frommakefile
ARG REGISTRY=frommakefile

FROM ${REGISTRY}/${DOCKERSRC}-debug_${DISTRIB}:${ARCH}

RUN apt-get update && apt-get -y -q install --no-install-recommends unzip openjdk-17-jre-headless python-is-python3 wget ca-certificates && apt-get clean && rm -rf /var/cache/apt/* /var/lib/apt/lists/*

RUN mkdir -p /opt/Nzbhydra2

COPY --chmod=755 entrypoint/nzbhydra2.sh /usr/local/bin/

WORKDIR /opt/Nzbhydra2

RUN wget "https://github.com/theotherp/nzbhydra2/releases/download/v7.12.3/nzbhydra2-7.12.3-amd64-linux.zip"

RUN unzip nzbhydra2-7.12.3-amd64-linux.zip

RUN chmod +x /opt/Nzbhydra2/nzbhydra2wrapperPy3.py

EXPOSE 5076

ENTRYPOINT ["/usr/local/bin/nzbhydra2.sh"]
