ARG ARCH
ARG DISTRIB
ARG DOCKERSRC
ARG REGISTRY

ARG HTTP_PROXY
ARG HTTPS_PROXY

FROM ${REGISTRY}/${DOCKERSRC}_${DISTRIB}:${ARCH}
ENV HTTP_PROXY=$HTTP_PROXY
ENV HTTPS_PROXY=$HTTPS_PROXY

RUN apt-get update && apt-get -y -q install --no-install-recommends iproute2 netbase autofs procps nfs-common net-tools transmission-daemon curl ca-certificates && apt-get clean && rm -rf /var/cache/apt/* /var/lib/apt/lists/*

# Clear proxy variables for final image
ENV HTTP_PROXY=
ENV HTTPS_PROXY=

ADD entrypoint/transmission.sh /usr/local/transmission.sh
RUN chmod 755 /usr/local/transmission.sh

RUN echo "/mnt/nfs        /transmission/auto.syno --ghost,--timeout=60" > /etc/auto.master.d/syno.autofs

COPY conf/transmission.json /etc/transmission-daemon/settings.json

EXPOSE 9091/tcp

ENTRYPOINT ["/usr/local/transmission.sh"]
