ARG ARCH=frommakefile
ARG DISTRIB=frommakefile
ARG DOCKERSRC=frommakefile
ARG REGISTRY=frommakefile

FROM ${REGISTRY}/${DOCKERSRC}_${DISTRIB}:${ARCH}

RUN apt-get update && apt-get -y -q install --no-install-recommends openvpn iptables curl ca-certificates net-tools procps lsof iproute2 && apt-get clean && rm -rf /var/cache/apt/* /var/lib/apt/lists/*

RUN groupadd vpn
RUN mkdir /vpn

ADD http://www.privateinternetaccess.com/openvpn/ca.crt /vpn/

COPY entrypoint/openvpn.sh /usr/bin/

ENTRYPOINT ["openvpn.sh"]

